#!/usr/bin/env zsh

zc_relative_path() {
  if [[ -z "$1" ]]; then
    zc_print "zc_path_relative: No path provided" --type err
    return 1
  fi

  echo $(realpath "$1" --relative-to="${2:-$ZCUSTOM}")
}
