#!/usr/bin/env zsh

__zc_debug_print() {
  if [[ "$ZDEBUG" == true ]]; then
    # local $message = "$1"
    # shift

    # local formatted_message
    # formatted_message=$(printf "$message" "$@")
    print -P "%F{yellow}[DEBUG]%f ${indent}${1}"
  fi
}
